# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f7e3f26b88a6cc93c5b32cbe9fb2745712fa8a869be0b89e6720950a44254e6353c0808139b01105c95b654781aca44a10a06e4b46ca79cb4fbba7f5d6bff68

test:
  secret_key_base: 4d71f0475cdb3174fccd0fb70fa26dd70d3bd0da610a0237159ccde6a25b6d076a2a2a23e1dd56eb0bb53b04a47428c5ceb7d1afac66c57595ee763e934c7da1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
